ayla/urls.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
@Project ：test_django 
@File    ：urls.py
@IDE     ：PyCharm 
@Author  ：陈康
@Date    ：2021/8/5 22:29 
'''
from django.conf.urls import url
from booktest import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^area/$', views.search_area),
]

booktest/urls.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
@Project ：test_django 
@File    ：urls.py
@IDE     ：PyCharm 
@Author  ：陈康
@Date    ：2021/7/7 22:05 
'''
from django.conf.urls import url
from booktest import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^area/$', views.search_area),
]
# 方式1：位置参数
# 直接使用小括号，通过位置参数传递给视图。
# url(r'^delete(\d+)/$',views.show_arg),
# def show_arg(request, id):
#     return HttpResponse('show arg %s' % id)

# 方式2：关键字参数
# 其中?P部分表示为这个参数定义的名称为id，可以是其它名称，起名做到见名知意。
# url(r'^delete(?P<id1>\d+)/$', views.show_arg),
# def show_arg(request, id1):
#     return HttpResponse('show arg %s' % id1)

test_django/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    url(r'^', include('booktest.urls')),
    url(r'^b/', include('booktest.urls')),
    url(r'^u/', include('login.urls')),
    url(r'^a/', include('login.urls')),
]

booktest/models.py
from django.db import models
# 设计和表对应的类 模型类
# Create your models here.

'''
管理器
属性objects：管理器，是models.Manager类型的对象，用于与数据库进行交互。
当没有为模型类定义管理器时，Django会为每一个模型类生成一个名为objects的管理器，自定义管理器后，Django不再生成默认管理器objects
管理器是Django的模型进行数据库操作的接口，Django应用的每个模型类都拥有至少一个管理器。Django支持自定义管理器类，继承自models.Manager。
自定义管理器类主要用于两种情况
    1.修改原始查询集，重写all()方法
    2.向管理器类中添加额外的方法，如向数据库中插入数据。
为模型类BookInfo定义管理器books语法如下：
    class BookInfo(models.Model):
        ...
        books = models.Manager()
'''
class BookInfoManager(models.Manager):
    '''图书管理器'''
    def all(self):
        # 默认查询未删除的图书信息
        # 调用父类的成员语法为：super().方法名
        return super().all().filter(isDelete=False)

    def create_book(self,book_name):
        '''创建图书'''
        book = self.model()
        book.book_name = book_name
        book.book_read = 0
        book.book_comment = 0
        book.isDelete = False
        #将数据插入数据表
        book.save()
        return book

'''基本类'''
#图书类
class BookInfo(models.Model):
    '''图书模型类'''
    books = BookInfoManager()
    # 图书ID:django会自动生成一个自增的ID
    # 图书名称 CharField说明是一个字符串 max_length指定字符串的最大长度
    book_name = models.CharField('图书名', max_length=20)
    #出版日期 DateField说明是一个日期类型
    # book_pub_date = models.DateField(auto_now=True)
    #阅读量
    book_read = models.IntegerField(default=0)
    #评论量
    book_comment = models.IntegerField(default=0)
    #删除标记
    isDelete = models.BooleanField(default=False)

    #定义元选项
    class Mete:
        db_table = 'bookinfo'

class RoleInfo(models.Model):
    '''角色人物模型类'''
    '''
    blank:
    若为True，该字段允许为空。默认是False。
    注意它和null的不同。null是纯粹和数据库相关的，而’blank’则是和验证相关的。
    若一个字段的blank=True，表单的验证将会允许实例带一个空值。反之则不行
    '''
    #角色名
    role_name = models.CharField('角色名',max_length=20,help_text='角色名不能为空')
    #性别
    sex = (
        ('0','男'),
        ('1','女')
    )
    gender = models.CharField('性别',max_length=1,choices=sex)
    #备注
    comment = models.CharField('备注',max_length=100,blank=True)
    #与图书的关系外键
    role_book = models.ForeignKey('BookInfo', on_delete=models.CASCADE)

    # 定义元选项
    class Mete:
        db_table = 'roleinfo'

class AreaInfo(models.Model):
    '''定义地区模型类、存储省、市、区县信息'''
    area_name = models.CharField('地区名称', max_length=30)
    area_parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

booktest/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

from booktest.models import AreaInfo, BookInfo


def index(request):
    meun = [{
        'title': '江西' #// 一级菜单
        , 'children': [{
            'title': '南昌' #// 二级菜单
            , 'children': [{
                'title': '高新区' #// 三级菜单
                       #//…… // 以此类推，可无限层级
    }]
    }]
    }, {
        'title': '陕西' #// 一级菜单
        , 'children': [{
            'title': '西安' #// 二级菜单
        }]
    }]
    print(BookInfo.books.all())
    # context = {'title': "图书列表",'list': BookInfo.books.all(),'meun':meun}
    # context = json.dumps(context)
    datalist = [{'site': '自强学堂', 'author': meun}]
    # 只要列表能接收
    # datalist=[[93, 93, 0, 100.01], [20, 23, 26, 29]]
    dl = json.dumps(datalist)
    return render(request, 'booktest/index.html', {'datalist': dl})
    # return render(request, 'booktest/index.html', context)

def search_area(request):
    '''查询地区的信息'''
    area = AreaInfo.objects.get(pk=440100)
    print('area',area)
    return render(request, 'booktest/area.html',{'area':area})

def cookie_set(request):
    '''设置cookie'''
    response = HttpResponse("<h1>设置Cookie，请查看响应报文头</h1>")
    response.set_cookie('h1', '你好')
    return response

def cookie_get(request):
    '''读取cookie'''
    response = HttpResponse("读取Cookie，数据如下：<br>")
    if 'h1' in request.COOKIES:
        response.write('<h1>' + request.COOKIES['h1'] + '</h1>')
    return response




def search(request):
    '''
    1.2.1 查询
    exact：表示判断等于，和 = 差不多。
        list=BookInfo.objects.filter(id__exact=1) list=BookInfo.objects.filter(id=1)

    1.2.2 模糊查询
    contains：是否包含 如果要包含%无需转义，直接写即可。
        list = BookInfo.objects.filter(btitle__contains='斗')
    startswith、endswith：以指定值开头或结尾。
        list = BookInfo.objects.filter(btitle__endswith='天')

    1.2.3 空查询
    isnull：是否为null。
        list = BookInfo.objects.filter(btitle__isnull=False)

    1.2.4 范围查询
    in：是否包含在范围内。
        list = BookInfo.objects.filter(id__in=[1, 3, 5])

    1.2.5 比较查询
    gt、gte、lt、lte：大于、大于等于、小于、小于等于。
        list = BookInfo.objects.filter(id__gt=3)
    不等于的运算符，使用exclude()过滤器。
        list = BookInfo.objects.exclude(id=3)

    1.2.6 日期查询
    year、month、day、week_day、hour、minute、second：对日期时间类型的属性进行运算
        list = BookInfo.objects.filter(bpub_date__year=2009)
        查询2008年12月14日后发表的图书
        list = BookInfo.objects.filter(bpub_date__gt=date(2008, 12, 14))

    1.3 F对象
    两个属性怎么比较呢？ 答：使用F对象，被定义在django.db.models中
    F(属性名)
        查询阅读量大于等于评论量的图书。
        list = BookInfo.objects.filter(bread__gte=F('bcomment'))
        查询阅读量大于2倍评论量的图书。
        list = BookInfo.objects.filter(bread__gt=F('bcomment') * 2)

    多个过滤器逐个调用表示逻辑与关系，同sql语句中where部分的and关键字
        查询阅读量大于20，并且编号小于3的图书。
        list=BookInfo.objects.filter(bread__gt=20,id__lt=3) 或 list=BookInfo.objects.filter(bread__gt=20).filter(id__lt=3)

    1.4 Q对象
    需要实现逻辑或or的查询，需要使用Q()对象结合|运算符，Q对象被义在django.db.models中
    Q(属性名__运算符=值)
    Q对象可以使用&、|连接，&表示逻辑与，|表示逻辑或。
        查询阅读量大于20，或编号小于3的图书，只能使用Q对象实现。
        list = BookInfo.objects.filter(Q(bread__gt=20) | Q(pk__lt=3))
    Q对象前可以使用~操作符，表示非not
        查询编号不等于3的图书。
        list = BookInfo.objects.filter(~Q(pk=3))

    1.5 聚合函数
    使用aggregate()过滤器调用聚合函数。聚合函数包括：Avg，Count，Max，Min，Sum，被定义在django.db.models中
        查询图书的总阅读量。
        sum = BookInfo.objects.aggregate(Sum('bread'))
    注意aggregate的返回值是一个字典类型，格式如下：
        {'聚合类小写__属性名':值}----------->>>>>>>>{'sum__bread':3}
    使用count时一般不使用aggregate()过滤器。
        count = BookInfo.objects.count()

    2.2 查询集的缓存
    情况一：如下是两个查询集，无法重用缓存，每次查询都会与数据库进行一次交互，增加了数据库的负载。
        [book.id for book in BookInfo.objects.all()]
        [book.id for book in BookInfo.objects.all()]
    情况二：经过存储后，可以重用查询集，第二次使用缓存中的数据。
        list=BookInfo.objects.all()
        [book.id for book in list]
        [book.id for book in list]
    2.3 限制查询集
    可以对查询集进行取下标或切片操作，等同于sql中的limit和offset子句。
        注意：不支持负数索引。
        示例：获取第1、2项，运行查看。
        list=BookInfo.objects.all()[0:2]
    '''

templates/booktest/area.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>地区</title>
</head>
<body>
当前地区: {{ area.area_name }}
<hr>
上级地区: {{ area.area_parent.area_name }}
<hr>
下级地区:
<ul>
    {% for a in area.areainfo_set.all %}
    <li>{{ a.area_name }}</li>
    {% endfor %}
</ul>
</body>
</html>

templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>啊啊啊啊啊啊啊啊</title>
    <link rel="stylesheet" href="{% static "/layui/css/layui.css" %}">
    <script src={% static "/layui/layui.js" %}></script>
{% block script1 %}

    {% endblock %}
</head>
<body>
<ul class="layui-nav">
  {% if request.session.is_login %}
      <li class="layui-nav-item">
        <a href="">控制台<span class="layui-badge">9</span></a>
      </li>
      <li class="layui-nav-item">
        <a href="">个人中心<span class="layui-badge-dot"></span></a>
      </li>
      <li class="layui-nav-item">
        <a href=""><img src="" class="layui-nav-img">{{ request.session.user_name }}</a>
        <dl class="layui-nav-child">
          <dd><a href="javascript:;">修改信息</a></dd>
          <dd><a href="javascript:;">安全管理</a></dd>
          <dd><a href="/u/logout/" class="btn">登出</a></dd>
        </dl>
      </li>
</ul>
      <h1>陈康的图书馆</h1>
          {% block content %}

          {% endblock %}
  {% else %}
      <li class="layui-nav-item">
        <a href="/u/register/">注册</a>
      </li>
      <li class="layui-nav-item">
        <a href="/u/login/">登录</a>
      </li>
  {% endif %}

</body>
</html>

templates/booktest/index.html
{% extends "booktest/base.html" %}
{% block script1 %}
    <script>
    var aaa = JSON.parse('{{ datalist|safe }}');
  console.log(aaa)
  layui.use('tree', function(){
    var tree = layui.tree;
    //渲染

     var setData = [{
        'title': '江西' // 一级菜单
        , 'children': [{
            'title': '南昌' // 二级菜单
            , 'children': [{
                'title': '高新区' // 三级菜单
                       //…… // 以此类推，可无限层级
    }]
    }]
    }, {
        'title': '陕西' // 一级菜单
        , 'children': [{
            'title': '西安' // 二级菜单
        }]
    }]
    var inst1 = tree.render({
      elem: '#test1'  //绑定元素
      ,data: setData
    });
  });

  </script>

    {% endblock %}
<body>

{% block content %}
    <div id="test1"></div>
<ul class="layui-nav layui-nav-tree" lay-filter="test">
<!-- 侧边导航: <ul class="layui-nav layui-nav-tree layui-nav-side"> -->
  <li class="layui-nav-item layui-nav-itemed">
    <a href="javascript:;">默认展开</a>
    <dl class="layui-nav-child">
      <dd><a href="javascript:;">选项1</a></dd>
      <dd><a href="javascript:;">选项2</a></dd>
      <dd><a href="">跳转</a></dd>
    </dl>
  </li>
  <li class="layui-nav-item">
    <a href="javascript:;">解决方案</a>
    <dl class="layui-nav-child">
      <dd><a href="">移动模块</a></dd>
      <dd><a href="">后台模版</a></dd>
      <dd><a href="">电商平台</a></dd>
    </dl>
  </li>
  <li class="layui-nav-item"><a href="">产品</a></li>
  <li class="layui-nav-item"><a href="">大数据</a></li>
</ul>

{% endblock %}

</body>

templates/booktest/test.html
{% extends "booktest/base.html" %}
{% block content %}
    <ul class="layui-nav layui-nav-tree" lay-filter="test">
<!-- 侧边导航: <ul class="layui-nav layui-nav-tree layui-nav-side"> -->
  <li class="layui-nav-item layui-nav-itemed">
    <a href="javascript:;">默认展开</a>
    <dl class="layui-nav-child">
      <dd><a href="javascript:;">选项1</a></dd>
      <dd><a href="javascript:;">选项2</a></dd>
      <dd><a href="">跳转</a></dd>
    </dl>
  </li>
  <li class="layui-nav-item">
    <a href="javascript:;">解决方案</a>
    <dl class="layui-nav-child">
      <dd><a href="">移动模块</a></dd>
      <dd><a href="">后台模版</a></dd>
      <dd><a href="">电商平台</a></dd>
    </dl>
  </li>
  <li class="layui-nav-item"><a href="">产品</a></li>
  <li class="layui-nav-item"><a href="">大数据</a></li>
</ul>
<h1>{{ title }}</h1>
    {% for b in list %}
        <tr>
            <td>{{ b.id }}</td>
            <td>{{ b.book_name }}</td>
            <td>{{ b.book_read }}</td>
            <td>{{ b.book_comment }}</td>
        </tr>
    {% endfor %}
{% endblock %}